name: Deploy Streamlit App

on:
  push:
    branches:
      - main # Ubah sesuai dengan cabang yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Versi Python yang Anda gunakan

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit

      - name: Deploy to Streamlit
        run: |
          streamlit run app.py  # Ubah dengan path ke file Streamlit Anda
